version: "3"
services:
    database:
      container_name: csms-database
      image: mysql:debian
      ports:
       - "3306:3306"  
      environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=csms
         - TZ=Europe/Helsinki
      volumes:
         - ./mysql:/docker-entrypoint-initdb.d/:ro
      command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_swedish_ci']
